version: '3.3'
services:
    database:
        container_name: openelisglobal-database 
        image: postgres:9.5
        ports:
            - "15432:5432"
        restart: always
        env_file:
            - ./dev/database/database.env
        volumes:
              # preserves the database between containers
            - db-data:/var/lib/postgresql/data                
              # files here will run on install
            - ./dev/database/dbInit:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "clinlims", "-U", "clinlims" ]
            timeout: 45s
            interval: 10s
            retries: 10 
            
#     oe.openelis.org:
#         container_name: openelisglobal-webapp 
#         image: openelisglobal
#         depends_on:
#             - database
#         ports:
#             - "8080:8080"
#             - "8443:8443"
#         restart: always
#         environment:
     #       context.xml doesn't seem to be able to pick up environment variables directly, so we are passing them in as CATALINA_OPTS
#             - CATALINA_OPTS= -Ddatasource.url=jdbc:postgresql://database:5432/clinlims?currentSchema=clinlims -Ddatasource.username=clinlims -Ddatasource.password=clinlims
#         volumes:
#             - ./dev/plugins:/var/lib/openelis-global/plugins
#             - ./dev/tomcat/oe_server.xml:/usr/local/tomcat/conf/server.xml
#         secrets:
#             - source: keystore
#             - source: truststore
#             - source: common.properties
            
    fhir.openelis.org:
        container_name: hapi-fhir-jpaserver
        image: hapiproject/hapi:v5.4.0
        depends_on:
            - database
        ports:
            - "8081:8080"
            - "8444:8443"
        networks:
            - default
        restart: always
        environment:
          SPRING_CONFIG_LOCATION: file:///run/secrets/hapi_application.yaml
          JAVA_OPTS: "-Djavax.net.ssl.trustStore=/run/secrets/truststore  
                      -Djavax.net.ssl.trustStorePassword=testtest 
                      -Djavax.net.ssl.trustStoreType=pkcs12  
                      -Djavax.net.ssl.keyStore=/run/secrets/keystore  
                      -Djavax.net.ssl.keyStorePassword=testtest  
                      -Djavax.net.ssl.keyStoreType=pkcs12"
                      
                      
        extra_hosts:
#    this should be the loopback to the docker host. 
#    run 
#    /sbin/ip route|awk '/default/ { print $3 }' 
#    inside the container to make sure the ip address is correct
#    make sure connections to 8446 are allowed by your firewall
# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' hapi-fhir-jpaserver
            - host.openelis.org:172.26.0.3

        volumes:
            - ./dev/tomcat/hapi_server.xml:/usr/local/tomcat/conf/server.xml
           
        secrets:
            - source: hapi_application.yaml
            - source: common.properties
            - source: keystore
            - source: truststore
            
volumes:
  db-data:            
secrets:
  keystore:
    file: ./dev/https/greg.dev.openelis.org.keystore.p12
  truststore:
    file: ./dev/https/greg.dev.openelis.org.truststore.p12
  common.properties:
    file: ./dev/properties/common.properties  
  hapi.properties:
    file: ./dev/properties/hapi.properties
  hapi_application.yaml:
    file: ./dev/properties/hapi_application.yaml
    
    
