version: '3.3'
# lines starting with a #db and #port will be uncommented when setup with a docker database
services:
#db    db.openelis.org:
#db        container_name: [% db_name %]
#db        image: postgres:9.5
#db        ports:
#db            - "[% db_host_port %]:5432"
#db        networks:
#db            - default
#db        restart: always
#db        env_file:
#db            - [% db_env_dir %]database.env
#db        environment:
#db            - TZ=[% timezone %]
#db        volumes:
#db              # preserves the database between containers
#db            - [% db_data_dir %]:/var/lib/postgresql/data                
#db              # files here will run on install
#db            - [% db_init_dir %]:/docker-entrypoint-initdb.d    
#db              # values must match values in DatabaseBackup.pl
#db            - [% db_backups_dir %]:[% docker_backups_dir %]   
#db        healthcheck:
#db            test: [ "CMD", "pg_isready", "-q", "-d", "clinlims", "-U", "clinlims" ]
#db            timeout: 45s
#db            interval: 10s
#db            retries: 10 
            
    oe.openelis.org:
        container_name: [% oe_name %]
        image: openelisglobal
#db        depends_on:
#db            - db.openelis.org
        ports:
            - "8080:8080"
            - "8443:8443"
        networks:
            default:
                ipv4_address: 172.20.1.121
        restart: always
        environment:
            - TZ=[% timezone %]
              # context.xml doesn't seem to be able to pick up environment variables directly, so we are passing them in as CATALINA_OPTS
            - CATALINA_OPTS= -Ddatasource.url=jdbc:postgresql://[% db_host %]:[% db_port %]/clinlims -Ddatasource.username=clinlims
        volumes:
            - [% plugins_dir %]:/var/lib/openelis-global/plugins
            - [% etc_dir %]oe_server.xml:/usr/local/tomcat/conf/server.xml
            - [% logs_dir %]:/var/lib/openelis-global/logs
            - [% tomcat_logs_dir %]:/usr/local/tomcat/logs
        secrets:
            - source: client_facing_keystore
            - source: keystore
            - source: truststore
            - source: datasource.password
            - source: common.properties
            - source: extra.properties
    
    fhir.openelis.org:
        container_name: [% fhir_api_name %]
        image: hapiproject/hapi:v5.4.0
#db        depends_on:
#db            - db.openelis.org
        ports:
            - "8081:8080"
            - "8444:8443"
        networks:
            - default
        restart: always
        environment:
          SPRING_CONFIG_LOCATION: file:///run/secrets/hapi_application.yaml
          TZ: [% timezone %]
          JAVA_OPTS: "-Djavax.net.ssl.trustStore=/run/secrets/truststore 
                      -Djavax.net.ssl.trustStorePassword=[% truststore_password %] 
                      -Djavax.net.ssl.trustStoreType=pkcs12 
                      -Djavax.net.ssl.keyStore=/run/secrets/keystore 
                      -Djavax.net.ssl.keyStorePassword=[% keystore_password %] 
                      -Djavax.net.ssl.keyStoreType=pkcs12"
          
        volumes:
            - [% etc_dir %]hapi_server.xml:/usr/local/tomcat/conf/server.xml
        secrets:
            - source: hapi_application.yaml
            - source: common.properties
            - source: keystore
            - source: truststore
            
secrets:
  datasource.password:
    file: [% secrets_dir %]datasource.password  
  common.properties:
    file: [% secrets_dir %]common.properties  
  extra.properties:
    file: [% secrets_dir %]extra.properties  
#  hapi.properties:
#    file: [% secrets_dir %]hapi.properties
  hapi_application.yaml:
     file: [% secrets_dir %]hapi_application.yaml
  client_facing_keystore:
    file: [% etc_dir %]client_facing_keystore
  keystore:
    file: [% etc_dir %]keystore
  truststore:
    file: [% etc_dir %]truststore
    
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
